SELECT EMPLOYEE.FIRSTNAME, EMPLOYEE.LASTNAME, CONTRACT.SERVICE
  FROM EMPLOYEE
INNER JOIN WORKSON
ON EMPLOYEE.ID=WORKSON.EMPLOYEEID
  INNER JOIN CONTRACT
    ON CONTRACT.ID=WORKSON.CONTRACTID;

SELECT * FROM EMPLOYEE;


SELECT DISTINCT EMPLOYEE.ID, EMPLOYEE.FirstName, Employee.LastName
FROM EMPLOYEE
  INNER JOIN WORKSON
    ON EMPLOYEE.ID=WORKSON.EMPLOYEEID
  INNER JOIN CONTRACT
    ON CONTRACT.ID=WORKSON.CONTRACTID
WHERE CONTRACT.SERVICE='Cloud' && EMPLOYEE.ID NOT IN (SELECT EMPLOYEE.ID
                                          FROM EMPLOYEE
                                            INNER JOIN WORKSON
                                              ON EMPLOYEE.ID=WORKSON.EMPLOYEEID
                                            INNER JOIN CONTRACT
                                              ON CONTRACT.ID=WORKSON.CONTRACTID
                                          WHERE CONTRACT.SERVICE!='Cloud');

SELECT DISTINCT EMPLOYEE.ID,EMPLOYEE.FIRSTNAME, EMPLOYEE.LASTNAME
FROM EMPLOYEE
  INNER JOIN WORKSON
    ON EMPLOYEE.ID=WORKSON.EMPLOYEEID
  INNER JOIN CONTRACT
    ON CONTRACT.ID=WORKSON.CONTRACTID
WHERE CONTRACT.SERVICE='Cloud';


SELECT EMPLOYEE.FIRSTNAME, EMPLOYEE.LASTNAME, CONTRACT.SERVICE
FROM EMPLOYEE
  INNER JOIN WORKSON
    ON EMPLOYEE.ID=WORKSON.EMPLOYEEID
  INNER JOIN CONTRACT
    ON CONTRACT.ID=WORKSON.CONTRACTID
WHERE (CONTRACT.SERVICE='Cloud' AND CONTRACT.SERVICE=('On-premises'));


SELECT EMPLOYEE.FIRSTNAME, EMPLOYEE.LASTNAME, CONTRACT.SERVICE
FROM EMPLOYEE
INNER JOIN WORKSON
    ON EMPLOYEE.ID=WORKSON.EMPLOYEEID
INNER JOIN CONTRACT
    ON CONTRACT.ID=WORKSON.CONTRACTID
WHERE (CONTRACT.SERVICE='Cloud' AND CONTRACT.SERVICE NOT IN ('On-premises'));


SELECT EMPLOYEE.FIRSTNAME, EMPLOYEE.LASTNAME, EMPLOYEE.ROLE
FROM EMPLOYEE
WHERE ROLE='Developer';


SELECT EMPLOYEE.FIRSTNAME, EMPLOYEE.LASTNAME, CONTRACT.annualContractValue
FROM EMPLOYEE
  INNER JOIN WORKSON
    ON EMPLOYEE.ID=WORKSON.EMPLOYEEID
  INNER JOIN CONTRACT
    ON CONTRACT.ID=WORKSON.CONTRACTID
WHERE CONTRACT.annualContractValue>=20000;


SELECT CONTRACT.ID, EMPLOYEE.FIRSTNAME, EMPLOYEE.LASTNAME
FROM CONTRACT
  INNER JOIN WORKSON
    ON CONTRACT.ID=WORKSON.CONTRACTID
  INNER JOIN EMPLOYEE
    ON EMPLOYEE.ID=WORKSON.EMPLOYEEID
WHERE EMPLOYEE.FIRSTNAME='VAN'
  &&
 EMPLOYEE.LASTNAME='DAVID';

SELECT * FROM Contract WHERE Service = 'Gold';